### ISSUE TITLE
Can this SDK connect to a enterprise exchange server?

### ISSUE THREAD

**Issue by chenxiemin** [OfficeDev/O365-Android-MeetingFeedback#7]
My company has our own mail exchange server so I'm wondering that if this SDK can get the meeting list / calendar from our own exchange server? Thanks very much.

**Comment by ricalo** [comment]
Hi @chenxiemin,

We use ADAL to get tokens from Office 365/Azure AD. Unfortunately, ADAL doesn't support on-premises environments.

However, it looks like the [EWS Java API](https://github.com/OfficeDev/ews-java-api/wiki/Getting-Started-Guide) could meet your requirements.

Let us know how things go.
